spring.application.name=MakerManager-Server

# Connessione al database MySQL locale
spring.datasource.url=jdbc:mysql://localhost:3306/672516?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione Hibernate (Crea le tabelle in automatico)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurazione dell'admin di default
admin.default.nickname=giuse27-admin
admin.default.email=giuse27.admin@makermanager.com
admin.default.password=password_segretissima_1234