### Variabili
@baseUrl = http://localhost:8080

### -----------------------------------------------------------------------
### INIZIALIZZAZIONE
### -----------------------------------------------------------------------

### -----------------------------------------------------------------------
### Inizializza (o re-inizializza) il database dal JSON di caricamento
### -----------------------------------------------------------------------
# Cancella tutti i dati esistenti e ricarica da catalogo-iniziale.json
POST {{baseUrl}}/inizializza
